# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    cu.sld.ucmgt.directory: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${application.registry-config.password}@192.168.1.10:8761/eureka/

management:
  health:
    elasticsearch:
      enabled: false

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.1.10:5432/directory
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      pool-name: Hikari
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          oidc:
            provider: keycloak
            client-id: internal
            client-secret: internal
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak:9080/auth/realms/jhipster
  elasticsearch:
    rest:
      username: elastic
      password: elastic
      uris: http://192.168.1.10:9200
  servlet:
    multipart:
      file-size-threshold: 2KB
server:
  port: 8081

# ===================================================================
# App specific properties
# ===================================================================
application:
#  cors:
#    allowed-origins: 'http://localhost:3000'
#    allowed-methods: '*'
#    allowed-headers: '*'
#    exposed-headers: 'Authorization,Link,X-Total-Count,X-${application.clientApp.name}-alert,X-${application.clientApp.name}-error,X-${application.clientApp.name}-params'
#    allow-credentials: true
#    max-age: 1800
  cache: # Cache configuration
    time-to-live-seconds: 3600
    backup-count: 1
    management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
      enabled: false
      update-interval: 3
      url: http://192.168.1.10:8180/hazelcast-mancenter
  storage:
    upload-dir: /media/cesar/Stuff/Dev/java/ucm/directory/upload/
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.